---
env: local
port: 8080
site:
  protocol: http
  hostname: localhost:8080
debug: true
service:
  api:
    url: 'http://mafueng-api.youpin.city'
    app_username: 'web@mafueng.city'
    app_password: 'web_mafueng'
